# Generated by Django 3.2.23 on 2023-11-28 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('surname', models.CharField(max_length=45)),
                ('phone_number', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('surname', models.CharField(max_length=45)),
                ('phone_number', models.CharField(max_length=45)),
                ('license_number', models.CharField(max_length=45)),
                ('rating', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('start_address', models.CharField(max_length=100)),
                ('final_address', models.CharField(max_length=100)),
                ('client_delayed', models.BooleanField()),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxi.client')),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxi.driver')),
            ],
        ),
    ]
