# Generated by Django 3.2.23 on 2023-11-30 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='km',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
