# Generated by Django 3.2.23 on 2023-12-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0002_order_km'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='clients',
            field=models.ManyToManyField(related_name='some_name', through='taxi.Order', to='taxi.Client'),
        ),
    ]
