# Generated by Django 3.2.23 on 2023-12-04 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0003_driver_clients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='clients',
        ),
    ]
