# Generated by Django 3.2.23 on 2023-12-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0006_alter_driver_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='test',
            field=models.CharField(default=1, max_length=45),
            preserve_default=False,
        ),
    ]
