# Generated by Django 3.2.23 on 2023-12-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0007_client_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='test',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='clients',
        ),
        migrations.RemoveField(
            model_name='order',
            name='client_delayed',
        ),
        migrations.RemoveField(
            model_name='order',
            name='client_id',
        ),
        migrations.AddField(
            model_name='order',
            name='clients',
            field=models.ManyToManyField(related_name='order', to='taxi.Client'),
        ),
    ]
