# Generated by Django 3.2.23 on 2023-12-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0008_auto_20231204_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
